name: Deploying multiple Lambdas
on:
  push:
    branches:
      - main
jobs:
  lambdas:
    strategy:
      matrix:
        lambda: [whatToWatch_listItems,whatToWatch_createItem,whatToWatch_showItemById]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: zip -j ./build/source.zip ./src/*
      - run: aws lambda update-function-code --function-name=${{matrix.lambda}} --zip-file=fileb://./build/source.zip
